language: c

dist: xenial

# Choose operating systems.
os:
  - linux
  - osx
  - windows

# Choose compilers.
compiler:
  - clang
  - gcc

# Override default script.
script:
  - cmake . && cmake --build . && ctest --output-on-failure
