language: c

# root key configurations (defaults).
os: linux
dist: xenial

# OS and compiler configurations.
jobs:
  include:
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc
  - os: osx
  - os: windows

# Override default script.
script:
  - cmake . && cmake --build . && ctest --output-on-failure
